version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - staging
            severity: error
          meta:
            owner:
              - or+1337@elementary-data.com
            description: Checking for freshness anomalies by looking at a 1 hours
              period and comparing it to last 14 days
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    tests:
      - elementary.volume_anomalies
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - staging
            severity: error
          meta:
            owner:
              - or+1337@elementary-data.com
            description: Checking for freshness anomalies by looking at a 1 hours
              period and comparing it to last 14 days
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - staging
            severity: error
          meta:
            owner:
              - or+1337@elementary-data.com
            description: Checking for freshness anomalies by looking at a 1 hours
              period and comparing it to last 14 days
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "PII"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
    tests:
      - elementary.freshness_anomalies:
          time_bucket:
            period: hour
            count: 1
          sensitivity: 3
          days_back: 14
          backfill_days: 2
          timestamp_column: updated_at
          config:
            tags:
              - staging
            severity: error
          meta:
            owner:
              - or+1337@elementary-data.com
            description: Checking for freshness anomalies by looking at a 1 hours
              period and comparing it to last 14 days
