version: 2

models:
  - name: stg_customers
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "PII"]
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - relationships:
              to: ref('stg_signups')
              field: customer_id

          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
  - name: stg_orders
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    tests:
      - elementary.volume_anomalies
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
      - name: status
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true

      - name: customer_id
        data_tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
  - name: stg_payments
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "finance"]
    columns:
      - name: payment_id
        tests:
          - unique:
              config:
                severity: warn
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
      - name: payment_method
        tests:
          - accepted_values:
              config:
                severity: warn
              values: ["credit_card", "coupon", "bank_transfer", "gift_card"]

      - name: order_id
        data_tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
  - name: stg_signups
    meta:
      owner: "Idan"
    config:
      tags: ["staging", "PII"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: signup_id
        tests:
          - unique:
              config:
                severity: warn
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
      - name: customer_email
        tests:
          - unique
          - elementary.column_anomalies:
              sensitivity: 2
              config:
                severity: warn
              column_anomalies:
                - missing_count
      - name: customer_id
        data_tests:
          - dbt_utils.not_null_proportion:
              at_least: 0.5
              at_most: 1.0 # Optional
              group_by_columns: # Optional, Columns to group by before executing the test
                - group_id
              config:
                tags:
                  - Marketing
              meta:
                owner:
                  - daniel+999@elementary-data.com
                description: some test
