version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
        columns:
          - name: ad_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
          - name: customer_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
          - name: session_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
      - name: stg_app_sessions
        columns:
          - name: ad_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
          - name: customer_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
          - name: session_id
            tests:
              - dbt_utils.sequential_values:
                  interval: 1 # The gap between two sequential values
