version: 2

sources:
  - name: ads
    schema: elementary_demo
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
  - name: sessions
    schema: elementary_demo
    tables:
      - name: stg_website_sessions
        columns:
          - name: session_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
          - name: customer_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
          - name: ad_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
      - name: stg_app_sessions
        columns:
          - name: session_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
          - name: customer_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
          - name: ad_id
            tests:
              - unique:
                  config:
                    severity: error
                  meta:
                    owner:
                      - Maayan
                    description: The column should contain only unique values
