version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
        columns:
          - name: customer_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
          - name: ad_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
          - name: session_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
      - name: stg_app_sessions
        columns:
          - name: customer_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
          - name: ad_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
          - name: session_id
            tests:
              - unique:
                  config:
                    tags:
                      - stability
                    error_if: '>5'
                  meta:
                    owner:
                      - itamar+12@elementary-data.com
                    description: The column should contain only unique values, fails
                      if more than 5 are not unique
