version: 2

sources:
  - name: ads
    schema: jaffle_shop
    tables:
      - name: stg_google_ads
        columns:
          - name: ad_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
      - name: stg_facebook_ads
        columns:
          - name: ad_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
      - name: stg_instagram_ads

        columns:
          - name: ad_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
  - name: sessions
    schema: jaffle_shop
    tables:
      - name: stg_website_sessions
        columns:
          - name: session_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
          - name: ad_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
          - name: customer_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
      - name: stg_app_sessions
        columns:
          - name: ad_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
          - name: session_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
          - name: customer_id
            data_tests:
              - dbt_utils.not_null_proportion:
                  at_most: 1.0 # Optional
                  group_by_columns: # Optional, Columns to group by before executing the test
                    - group_id
                  config:
                    tags:
                      - sales
